version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
  - package-ecosystem: nix
    directory: "/"
    schedule:
      interval: daily
      time: "11:30"
    open-pull-requests-limit: 10
