build_darwin_arm64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  env:
    CACHIX_AUTH_TOKEN: ENCRYPTED[!f0f7fdb6a0c000065b7755062731ff7916cee8f510c95478d629e76a2c03604cfe46fe2ec4e74a4128ad0a0aea6d57e7!]
  install_nix_script: ./bin/install-nix.sh && echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf && echo "trusted-users = root admin" | sudo tee -a /etc/nix/nix.conf && sudo launchctl kickstart -k system/org.nixos.nix-daemon
  install_cachix_script: source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use kclejeune
  flake_check_script: source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && cachix watch-exec kclejeune -- nix flake check -v --show-trace

build_darwin_x86_64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  env:
    CACHIX_AUTH_TOKEN: ENCRYPTED[!f0f7fdb6a0c000065b7755062731ff7916cee8f510c95478d629e76a2c03604cfe46fe2ec4e74a4128ad0a0aea6d57e7!]
  install_rosetta_script: softwareupdate --install-rosetta --agree-to-license
  install_nix_script: arch -x86_64 ./bin/install-nix.sh && echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf && echo "trusted-users = root admin" | sudo tee -a /etc/nix/nix.conf && sudo launchctl kickstart -k system/org.nixos.nix-daemon
  install_cachix_script: source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use kclejeune
  flake_check_script: source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && cachix watch-exec kclejeune -- nix flake check -v --show-trace

build_linux_task:
  matrix:
    - container:
        image: nixos/nix:latest
        cpu: 4
        memory: 8G
    - arm_container:
        image: nixos/nix:latest
        cpu: 4
        memory: 8G
  env:
    CACHIX_AUTH_TOKEN: ENCRYPTED[!f0f7fdb6a0c000065b7755062731ff7916cee8f510c95478d629e76a2c03604cfe46fe2ec4e74a4128ad0a0aea6d57e7!]
  enable_flake_script: echo "experimental-features = nix-command flakes" | tee -a /etc/nix/nix.conf
  install_cachix_script: nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use kclejeune
  flake_check_script: cachix watch-exec kclejeune -- nix flake check -v --show-trace
