env:
  CIRRUS_SHELL: bash -il
  DARWIN_BUILD_IMAGE: ghcr.io/cirruslabs/macos-ventura-base:latest
  LINUX_BUILD_IMAGE: debian:11

build_template: &BUILD_TEMPLATE
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_TAG != "" || $CIRRUS_PR != "" || $CIRRUS_BUILD_SOURCE == ""
  name: build_${CIRRUS_OS}_${ARCH}
  timeout_in: 120m
  env:
    RUST_BACKTRACE: "1"
    CACHIX_AUTH_TOKEN: ENCRYPTED[!f0f7fdb6a0c000065b7755062731ff7916cee8f510c95478d629e76a2c03604cfe46fe2ec4e74a4128ad0a0aea6d57e7!]
    CACHIX_USER: kclejeune
    GITHUB_TOKEN: ENCRYPTED[!c4841aa1f80b4c94abe2742b4cf2cc998e9b7bbc4d1fa182abb50636b09272b6062bcd2be016a597c225e3715f784969!]
    NIX_INSTALLER_NO_CONFIRM: "true"
    NIX_INSTALLER_TAG: "v0.7.0"
    NIX_INSTALLER_EXTRA_CONF: |
      trusted-users = root admin @sudo @wheel
      extra-systems = ${ARCH//arm/aarch}-${CIRRUS_OS}
      substituters = https://cache.nixos.org https://kclejeune.cachix.org https://devenv.cachix.org
      trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= kclejeune.cachix.org-1:fOCrECygdFZKbMxHClhiTS6oowOkJ/I/dh9q9b1I4ko= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
      sandbox = false
      access-tokens = github.com=${GITHUB_TOKEN}
  install_nix_script: |
    curl -sL -o nix-installer https://install.determinate.systems/nix/nix-installer-${CIRRUS_ARCH}-${CIRRUS_OS} && chmod +x nix-installer
    if [[ "$CIRRUS_OS" = "linux" ]]; then
      ./nix-installer install linux --init none
    else
      ./nix-installer install
    fi
  install_cachix_script: nix profile install github:nixos/nixpkgs/nixpkgs-unstable#cachix && cachix use $CACHIX_USER
  flake_check_script: cachix watch-exec $CACHIX_USER -- nix flake check -j auto --system ${ARCH//arm/aarch}-${CIRRUS_OS} --show-trace --accept-flake-config

build_darwin_task:
  macos_instance:
    image: $DARWIN_BUILD_IMAGE
  matrix:
    - env:
        ARCH: arm64
    - env:
        ARCH: x86_64
  install_rosetta_script: softwareupdate --install-rosetta --agree-to-license
  <<: *BUILD_TEMPLATE

build_linux_task:
  matrix:
    - arm_container:
        image: $LINUX_BUILD_IMAGE
        cpu: 4
        memory: 16G
      env:
        ARCH: arm64
        USER: root
    - container:
        image: $LINUX_BUILD_IMAGE
        cpu: 4
        memory: 16G
      env:
        ARCH: x86_64
        USER: root
  install_env_script: apt update && apt -y install curl git sudo
  <<: *BUILD_TEMPLATE

