# global env values
env:
  CACHIX_AUTH_TOKEN: ENCRYPTED[!f0f7fdb6a0c000065b7755062731ff7916cee8f510c95478d629e76a2c03604cfe46fe2ec4e74a4128ad0a0aea6d57e7!]
  CIRRUS_SHELL: bash -il
  DARWIN_BUILD_IMAGE: ghcr.io/cirruslabs/macos-monterey-base:latest
  LINUX_BUILD_IMAGE: nixos/nix:latest
  SUDO: sudo

build_template: &BUILD_TEMPLATE
  enable_flake_script: echo "experimental-features = nix-command flakes" | $SUDO tee -a /etc/nix/nix.conf
  install_cachix_script: nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use kclejeune
  flake_check_script: cachix watch-exec kclejeune -- nix flake check -v --show-trace

build_darwin_task:
  macos_instance:
    image: $DARWIN_BUILD_IMAGE
  matrix:
    - env:
        CIRRUS_ARCH: arm64
    - env:
        CIRRUS_ARCH: x86_64
  install_rosetta_script: softwareupdate --install-rosetta --agree-to-license
  install_nix_script: arch -$CIRRUS_ARCH ./bin/install-nix.sh
  enable_trusted_users_script: echo "trusted-users = root admin" | $SUDO tee -a /etc/nix/nix.conf && sudo launchctl kickstart -k system/org.nixos.nix-daemon
  <<: *BUILD_TEMPLATE

build_linux_task:
  matrix:
    - arm_container:
        image: $LINUX_BUILD_IMAGE
        cpu: 4
        memory: 8G
      env:
        CIRRUS_ARCH: arm64
        SUDO: ""
    - container:
        image: $LINUX_BUILD_IMAGE
        cpu: 4
        memory: 8G
      env:
        CIRRUS_ARCH: x86_64
        SUDO: ""
  <<: *BUILD_TEMPLATE
