#! /usr/bin/env bash

OS=$(uname -s)

# check nix-shell installation
if ! type nix-shell > /dev/null; then
    echo "Installing multi-user Nix"
    if [[ $OS == "Darwin" ]]; then
        sh <(curl https://nixos.org/nix/install) --daemon --darwin-use-unencrypted-nix-store-volume
    else
        sh <(curl https://nixos.org/nix/install) --daemon
    fi
    source /etc/static/bashrc
fi

# back up necessary files if darwin
if [[ $OS == "Darwin" ]]; then
    if ! type brew > /dev/null; then
        echo "Installing Homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi
    cd /etc
    echo "Backing up /etc files"
    for file in bashrc shells skhdrc zprofile zshenv zshrc nix/nix.conf; do
        # if an /etc config file isn't a symlink, then we should move it
        [[ ! -L $file ]] && sudo mv $file "$file.backup" && echo "backed up $file"
    done
fi

# run darwin rebuild or nixOS rebuild to bootstrap system configuration
echo "Building nix configuration"
cd ~/.config/nixpkgs && nix-shell --run 'rebuild' &

# install apps with homebrew if on macOS
# [[ $OS == "Darwin" ]] && cd ~ && brew bundle install &

echo "Installation complete!"

