#! /usr/bin/env bash

OS=$(uname -s)

# check nix-shell installation
if ! type nix-shell > /dev/null; then
    echo "Installing multi-user Nix"
    if [[ $OS == "Darwin" ]]; then
        sh <(curl -L https://nixos.org/nix/install) --daemon --darwin-use-unencrypted-nix-store-volume
    else
        sh <(curl -L https://nixos.org/nix/install) --daemon
    fi
    source /etc/static/bashrc
fi
if ! type brew > /dev/null; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# # back up necessary files if darwin
# if [[ $OS == "Darwin" ]]; then

#     cd /etc
#     echo "Backing up /etc files"
#     for file in bashrc shells skhdrc zprofile zshenv zshrc nix/nix.conf; do
#         # if an /etc config file isn't a symlink, then we should move it
#         [[ ! -L $file ]] && sudo mv $file "$file.backup" && echo "backed up $file"
#     done
# fi

# change to stable nixpkgs
nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
# install home-manager and create the first generation
nix-channel --add https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz home-manager
nix-channel --update

# bootstrap first home-manager iteration
export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
nix-shell '<home-manager>' -A install

