#! /usr/bin/env bash

OS=$(uname -s)

# # check nix-shell installation
# if ! type nix-shell > /dev/null; then
#     echo "Installing multi-user Nix"
#     if [[ $OS == "Darwin" ]]; then
#         sh <(curl -L https://nixos.org/nix/install) --daemon --darwin-use-unencrypted-nix-store-volume
#     else
#         sh <(curl -L https://nixos.org/nix/install) --daemon
#     fi
#     source /etc/static/bashrc
# fi

# # check Homebrew installation
# if ! type brew > /dev/null; then
#     echo "Installing Homebrew"
#     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
# fi

# change to stable nixpkgs
nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
# install home-manager and create the first generation
nix-channel --add https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz home-manager

# # back up necessary files and install nix-darwin if darwin
if [[ $OS == "Darwin" ]]; then
    cd /etc
    echo "Backing up /etc files"
    for file in bashrc shells skhdrc yabairc zprofile zshenv zshrc nix/nix.conf; do
        # if an /etc config file isn't a symlink, then we should move it
        [[ -f $file ]] && [[ ! -L $file ]] && sudo mv $file "$file.backup" && echo "backed up $file"
    done

    # setup /run directory
    if ! grep -q '^run\b' /etc/synthetic.conf 2>/dev/null; then
        echo "setting up /etc/synthetic.conf..."
        echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
        /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B 2>/dev/null || true
    fi
    if ! test -L /run; then
        echo "setting up /run..."
        sudo ln -sfn private/var/run /run
    fi
    # add darwin channel
    nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
    nix-channel --update
    export NIX_PATH=darwin-config=$HOME/.config/nixpkgs/darwin/configuration.nix:$HOME/.nix-defexpr/channels:$NIX_PATH

    $(nix-build '<darwin>' -A system --no-out-link)/sw/bin/darwin-rebuild switch

    . /etc/static/bashrc

else
    nix-channel --update
    # bootstrap first home-manager iteration
    export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
    nix-shell '<home-manager>' -A install
fi

