name: build

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: build (${{ matrix.system }})
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: namespace-profile-default
            jobs: 2
          - system: aarch64-linux
            runner: namespace-profile-default-arm64
            jobs: 2
          - system: aarch64-darwin
            runner: namespace-profile-darwin-aarch64
            jobs: 4
    steps:
      - uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          determinate: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # extra-substituters = https://cache.kclj.io/kclejeune https://kclejeune.cachix.org https://install.determinate.systems https://noctalia.cachix.org
          # extra-trusted-public-keys = kclejeune:u0sa4anVXC4bKlzEsijdSlLyWVaEkApu6KWyDbbJMkk= kclejeune.cachix.org-1:fOCrECygdFZKbMxHClhiTS6oowOkJ/I/dh9q9b1I4ko= cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4=
          extra-conf: |
            accept-flake-config = true
            extra-substituters = https://cache.kclj.io/kclejeune https://install.determinate.systems https://noctalia.cachix.org
            extra-trusted-public-keys = kclejeune:u0sa4anVXC4bKlzEsijdSlLyWVaEkApu6KWyDbbJMkk= cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4=

      - name: Install nimbus
        run: nix profile add --accept-flake-config .#nimbus

      - name: Run flake checks
        env:
          NIMBUS_ENDPOINT: ${{ vars.NIMBUS_ENDPOINT }}
          NIMBUS_AUTH_TOKEN: ${{ secrets.NIMBUS_AUTH_TOKEN }}
        run: |
          nimbus watch-exec kclejeune nix flake check \
            --system ${{ matrix.system }} \
            --print-build-logs \
            --show-trace \
            --accept-flake-config \
            -j ${{ matrix.jobs }} \
            --max-substitution-jobs 4
